# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1220528782);
user_pref("app.update.lastUpdateTime.background-update-timer", 1220528782);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1220528782);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1220345366);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1232090039);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1220573182);
user_pref("browser.migration.version", 1);
user_pref("browser.offline", false);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://www2.webkit.org/perf/sunspider-0.9/sunspider-driver.html");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1b1pre");
user_pref("dom.max_script_run_time", 0);
user_pref("extensions.enabledItems", "{20a82645-c095-46ed-80e3-08825760534b}:0.0.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.9");
user_pref("extensions.lastAppVersion", "3.5.9");
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1269969982);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, Shift_JIS, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1272562003);
