# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.search.defaultenginename", "Google Search");
user_pref("browser.search.order.1", "Google Search");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.display.screen_resolution", 0);
user_pref("browser.startup.homepage", "http://pl.luna.tv/");
user_pref("general.useragent.locale", "pl");
user_pref("javascript.options.jit.content", true);
user_pref("network.cookie.prefsMigrated", true);
