# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.search.defaultenginename", "Google(日本語)");
user_pref("browser.search.order.1", "Google(日本語)");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.display.screen_resolution", 0);
user_pref("browser.startup.homepage", "http://www.luna.tv/");
user_pref("font.language.group", "ja");
user_pref("font.minimum-size.ja", 0);
user_pref("font.name.serif.ja", "ＭＳ Ｐ明朝");
user_pref("font.size.fixed.ja", 16);
user_pref("general.useragent.locale", "ja");
user_pref("intl.charset.detector", "ja_parallel_state_machine");
user_pref("intl.accept_languages", "ja, en-us, en");
user_pref("javascript.options.jit.content", true);
user_pref("network.cookie.prefsMigrated", true);
